/**
 * Stream API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@bunny.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CaptionModelAdd {
    /**
    * The unique srclang shortcode for the caption
    */
    'srclang'?: string;
    /**
    * The text description label for the caption
    */
    'label'?: string;
    /**
    * Base64 encoded captions file
    */
    'captionsFile'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "srclang",
            "baseName": "srclang",
            "type": "string"
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string"
        },
        {
            "name": "captionsFile",
            "baseName": "captionsFile",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CaptionModelAdd.attributeTypeMap;
    }
}

