/**
 * Stream API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@bunny.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class UpdateVideoModel {
    /**
    * The title of the video
    */
    'title'?: string;
    /**
    * The ID of the collection where the video belongs
    */
    'collectionId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "collectionId",
            "baseName": "collectionId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UpdateVideoModel.attributeTypeMap;
    }
}

